version: '3.8'

volumes:
  pg_data_production:
  static:

services:
  db:
    container_name: donor_base_db
    image: postgres:16
    restart: always
    env_file: ../.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: backend:latest # dummy
    restart: always
    env_file: ../.env
    volumes:
      - static:/backend_static
    depends_on:
      - db

 # here is the place for the nginx config
  nginx:
    image: nginx:1.25
    env_file: ../.env
